# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username if you have one
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name
custom: ["https://www.vladsnewsletter.com/"]
